"use server"

import prisma from "@/lib/prisma"
import { auth } from "@/auth"
import { revalidatePath } from "next/cache"
import { hash } from "bcryptjs"
import { z } from "zod"

// User type for raw query result (matching actual DB columns)
// User type for raw query result (matching actual DB columns)
interface DbUser {
  id: string
  email: string
  name: string | null
  password: string
  role: string
  jobTitle: string | null
  created_at: Date
  updated_at: Date
}

// Validation schemas
const createUserSchema = z.object({
  email: z.string().email("Email tidak valid"),
  name: z.string().min(2, "Nama minimal 2 karakter"),
  password: z.string().min(6, "Password minimal 6 karakter"),
  role: z.enum(["ADMIN", "PASTORAL_STAFF"]),
  jobTitle: z.string().optional(),
})

const updateUserSchema = z.object({
  id: z.string(),
  email: z.string().email("Email tidak valid").optional(),
  name: z.string().min(2, "Nama minimal 2 karakter").optional(),
  role: z.enum(["ADMIN", "PASTORAL_STAFF"]).optional(),
  jobTitle: z.string().optional(),
})

export type CreateUserInput = z.infer<typeof createUserSchema>
export type UpdateUserInput = z.infer<typeof updateUserSchema>

// Get all users with pagination (using raw SQL to bypass schema issues)
export async function getUsers(params: {
  page?: number
  limit?: number
  search?: string
} = {}) {
  const session = await auth()
  if (!session || session.user?.role !== "ADMIN") {
    throw new Error("Unauthorized")
  }

  const { page = 1, limit = 10, search = "" } = params
  const offset = (page - 1) * limit

  try {
    let users: DbUser[]
    let countResult: { count: bigint }[]

    if (search) {
      const searchPattern = `%${search}%`
      users = await prisma.$queryRaw<DbUser[]>`
        SELECT id, email, name, role, "jobTitle", created_at, updated_at
        FROM users 
        WHERE name ILIKE ${searchPattern} OR email ILIKE ${searchPattern}
        ORDER BY email ASC
        LIMIT ${limit} OFFSET ${offset}
      `
      countResult = await prisma.$queryRaw<{ count: bigint }[]>`
        SELECT COUNT(*) as count FROM users 
        WHERE name ILIKE ${searchPattern} OR email ILIKE ${searchPattern}
      `
    } else {
      users = await prisma.$queryRaw<DbUser[]>`
        SELECT id, email, name, role, "jobTitle", created_at, updated_at
        FROM users 
        ORDER BY email ASC
        LIMIT ${limit} OFFSET ${offset}
      `
      countResult = await prisma.$queryRaw<{ count: bigint }[]>`
        SELECT COUNT(*) as count FROM users
      `
    }

    const total = Number(countResult[0]?.count || 0)

    return {
      users: users.map(u => ({
        id: u.id,
        email: u.email,
        name: u.name,
        role: u.role,
        jobTitle: u.jobTitle,
        createdAt: u.created_at || new Date(),
      })),
      pagination: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    }
  } catch (error) {
    console.error("getUsers error:", error)
    throw new Error("Gagal mengambil data pengguna")
  }
}

// Get single user by ID
export async function getUserById(id: string) {
  const session = await auth()
  if (!session) {
    throw new Error("Unauthorized")
  }

  const users = await prisma.$queryRaw<DbUser[]>`
    SELECT id, email, name, role, "jobTitle", created_at, updated_at FROM users WHERE id = ${id} LIMIT 1
  `

  if (users.length === 0) {
    throw new Error("User not found")
  }

  const user = users[0]
  return {
    id: user.id,
    email: user.email,
    name: user.name,
    role: user.role,
    jobTitle: user.jobTitle,
    createdAt: user.created_at || new Date(),
  }
}

// Create new user
export async function createUser(input: CreateUserInput) {
  const session = await auth()
  if (!session || session.user?.role !== "ADMIN") {
    throw new Error("Unauthorized")
  }

  const validated = createUserSchema.parse(input)

  // Check if email already exists
  const existing = await prisma.$queryRaw<DbUser[]>`
    SELECT id FROM users WHERE email = ${validated.email} LIMIT 1
  `

  if (existing.length > 0) {
    throw new Error("Email sudah terdaftar")
  }

  // Hash password
  const hashedPassword = await hash(validated.password, 12)

  // Insert user
  // Insert user
  await prisma.user.create({
    data: {
      email: validated.email,
      name: validated.name,
      password: hashedPassword,
      role: validated.role,
      jobTitle: validated.jobTitle || null,
      // id is auto-generated by @default(uuid())
    }
  })

  revalidatePath("/admin/users")

  return { success: true, user: { email: validated.email, name: validated.name } }
}

// Update user
export async function updateUser(input: UpdateUserInput) {
  const session = await auth()
  if (!session || session.user?.role !== "ADMIN") {
    throw new Error("Unauthorized")
  }

  const validated = updateUserSchema.parse(input)
  const { id, email, name, role } = validated

  // Build update query dynamically
  if (email) {
    await prisma.$executeRaw`UPDATE users SET email = ${email} WHERE id = ${id}`
  }
  if (name) {
    await prisma.$executeRaw`UPDATE users SET name = ${name} WHERE id = ${id}`
  }
  if (role) {
    await prisma.$executeRaw`UPDATE users SET role = ${role} WHERE id = ${id}`
  }
  if (validated.jobTitle !== undefined) {
    await prisma.$executeRaw`UPDATE users SET "jobTitle" = ${validated.jobTitle} WHERE id = ${id}`
  }

  revalidatePath("/admin/users")

  return { success: true, user: { id, email, name } }
}

// Delete user
export async function deleteUser(id: string) {
  const session = await auth()
  if (!session || session.user?.role !== "ADMIN") {
    throw new Error("Unauthorized")
  }

  // Prevent deleting yourself
  if (session.user?.id === id) {
    throw new Error("Tidak dapat menghapus akun sendiri")
  }

  await prisma.$executeRaw`DELETE FROM users WHERE id = ${id}`

  revalidatePath("/admin/users")

  return { success: true }
}

// Get user stats
export async function getUserStats() {
  const session = await auth()
  if (!session || session.user?.role !== "ADMIN") {
    throw new Error("Unauthorized")
  }

  try {
    const [totalResult, pastoralResult] = await Promise.all([
      prisma.$queryRaw<{ count: bigint }[]>`SELECT COUNT(*) as count FROM users`,
      prisma.$queryRaw<{ count: bigint }[]>`SELECT COUNT(*) as count FROM users WHERE role = 'PASTORAL_STAFF'`,
    ])

    // Try to get pending evaluations, but don't fail if table doesn't exist
    let pendingCount = 0
    try {
      const pendingResult = await prisma.$queryRaw<{ count: bigint }[]>`
        SELECT COUNT(*) as count FROM evaluation_submissions WHERE "isFinal" = false
      `
      pendingCount = Number(pendingResult[0]?.count || 0)
    } catch {
      // Table doesn't exist yet, that's okay
      pendingCount = 0
    }

    return {
      total: Number(totalResult[0]?.count || 0),
      active: Number(totalResult[0]?.count || 0),
      pastoral: Number(pastoralResult[0]?.count || 0),
      pendingEvaluations: pendingCount,
    }
  } catch (error) {
    console.error("getUserStats error:", error)
    // Return defaults if query fails
    return {
      total: 0,
      active: 0,
      pastoral: 0,
      pendingEvaluations: 0,
    }
  }
}
